### ISSUE TITLE
Correccion de las unidades

### ISSUE THREAD

**Issue by Doxdrum** [restrepo/TCC#1]
https://github.com/restrepo/lagrangiano-del-modelo-estandar/blob/db9c7d3fe7e95111c00ab52eb1f7a13018469325/chapter1.tex#L1669

Debiera ser

       =& \SI{938.27208816+-0.00000029}{\MeV}\,, 

el `c^2` esta de mas. Aprovecho de modificar `MeV` a `\MeV`, que es el commando que entiende `siunitx`.

**Comment by restrepo** [comment]
Cambiado a \MeV. El c^2 es para enfatizar que es una masa

**Comment by Doxdrum** [comment]
Hola @restrepo , el comentario del `c^2` en las unidades es porque estas calculando la energia `m \, c^2` y no la masa. Por eso sobra el `c^2` en el denominador del resultado.

Saludos.

**Comment by restrepo** [comment]
Muchas gracias @Doxdrum, ya lo he quitado
